wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.6
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690360203.996511
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 23
      4: 3.11.4
      5: 0.15.6
      6: 4.31.0
      8:
      - 1
      - 5
